version: 2.1

commands:
  calculate-tag-name:
    description: "Calculates the target tag name for Docker image"
    steps:
      - run:
          name: Calculate tag to set for the built Docker image
          command: |
            if [ ! -z $CIRCLE_TAG ]; then
              TAG_VERSION=$CIRCLE_TAG
            elif [ "$CIRCLE_BRANCH" = "edge" ]; then
              TAG_VERSION=latest
            else
              TAG_VERSION=$CIRCLE_BRANCH;
            fi
            REVISION="$(git ls-remote https://github.com/transmission/transmission.git HEAD | awk '{print substr ($0, 0, 7)}')"

            echo "export IMAGE_TAG=$TAG_VERSION$TAG_DISTRO" >> $BASH_ENV
            echo "export REVISION='${CIRCLE_SHA1}-${REVISION}'" >> $BASH_ENV 


jobs:
  build:
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      DOCKER_BUILDKIT: "1"

    machine:
      image: ubuntu-2004:202111-02

    parameters:
      image-name:
        type: string
      build-context:
        type: string

    resource_class: large

    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y git qemu-user
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - calculate-tag-name
      - run:
          name: Set up buildx and build/push images
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name multiarch --driver docker-container --use
            docker buildx ls
            docker buildx build -t << parameters.image-name >>:$IMAGE_TAG --progress plain \
              --platform linux/arm64,linux/amd64 \
              --build-arg CI=1 \
              --build-arg REVISION=$REVISION \
              --push << parameters.build-context >>


workflows:

  build-docker-images:
    jobs:
      - build:
          name: build-transmission-vpn-edge-images
          context: dockerhub
          image-name: fluxstate/transmission-vpn-edge
          build-context: "."
          filters:
            branches:
              only:
                - edge
            tags:
              only: /^\d+\.\d+.*/

      - build:
          name: build-reverse-proxy-images
          context: dockerhub
          image-name: fluxstate/transmission-vpn-proxy-edge
          build-context: "proxy"
          filters:
            branches:
              only:
                - edge
            tags:
              only: /^\d+\.\d+.*/

      - build:
          name: build-rss-plugin-images
          context: dockerhub
          image-name: fluxstate/transmission-rss-edge
          build-context: "plugins/rss"
          filters:
            branches:
              only:
                - edge
            tags:
              only: /^\d+\.\d+.*/
